OPENAI_API_KEY = "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
"
OPENAI_MODEL = "gpt-4.1-mini"
